# Generated by Django 5.2.3 on 2025-06-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_technologytag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.technologytag'),
        ),
    ]
